<div class="footer">
  <div class="footer_social_images">
    <a href="http://twitter.com/mdoddzz"><img src="/images/Social/twitter.png"/></a>
    <a href="http://instagram.com/mdoddzz"><img src="/images/Social/instagram.png"/></a>
    <a href="https://uk.pinterest.com/mdoddzz/"><img src="/images/Social/pintrest.png"/></a>
    <a href="contact.php"><img src="/images/Social/email.png"/></a>
  </div>
  <h1>JOIN AND FOLLOW ME ON SOCIAL MEDIA</h1>
  <p>All content on this website is either property of Michael Dodd or labled for resuse. Created by Michael Dodd</p>
</div>
</body>
</html>
